inherit_gem:
  rubocop-rootstrap:
    - config/default_edge.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - '**/pagy.rb'
    - '**/init.rb'
    - '**/*.rake'
    - '*.erb'
    - '*.gemspec'

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/**/*

Naming/PredicateName:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/AbcSize:
  CountRepeatedAttributes: false

Style/OpenStructUse:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Naming/FileName:
  Exclude:
    - '**/lightning-api.rb'
    - '**/lightning-api_spec.rb'
