FROM ruby:3.1.0

RUN sed -i 's/http:/https:/' /etc/ssl/openssl.cnf
RUN apt update
RUN apt-get install -y libidn11
RUN mkdir /<%= app_dir %>
WORKDIR /<%= app_dir %>

COPY . /<%= app_dir %>

RUN gem update bundler
RUN bundle install

EXPOSE 4550
